In [1]:
import time
import pandas as pd
import polars as pl
import dask.dataframe as dd

t = time.time()
pd.read_csv("/media/amritesh/bytesviewhdd1/ai_stuf/crimson/data/AIS_2020_12_30.csv", engine='pyarrow')
print("Pandas:", time.time()-t)

t = time.time()
pl.read_csv("/media/amritesh/bytesviewhdd1/ai_stuf/crimson/data/AIS_2020_12_30.csv")
print("Polars:", time.time()-t)

t = time.time()
df = dd.read_csv("/media/amritesh/bytesviewhdd1/ai_stuf/crimson/data/AIS_2020_12_30.csv")
df = df.compute()
print("Dask:", time.time()-t)

Pandas: 0.7528235912322998
Polars: 0.21048283576965332
Dask: 11.686482667922974

In [2]:
import polars as pl

df_polar = pl.read_csv("/media/amritesh/bytesviewhdd1/ai_stuf/crimson/data/AIS_2020_12_30.csv")
df_polar.head()

shape: (5, 17)
┌───────────┬─────────────────┬──────────┬────────────┬───┬───────┬───────┬───────┬────────────────┐
│ MMSI      ┆ BaseDateTime    ┆ LAT      ┆ LON        ┆ … ┆ Width ┆ Draft ┆ Cargo ┆ TransceiverCla │
│ ---       ┆ ---             ┆ ---      ┆ ---        ┆   ┆ ---   ┆ ---   ┆ ---   ┆ ss             │
│ i64       ┆ str             ┆ f64      ┆ f64        ┆   ┆ i64   ┆ f64   ┆ i64   ┆ ---            │
│           ┆                 ┆          ┆            ┆   ┆       ┆       ┆       ┆ str            │
╞═══════════╪═════════════════╪══════════╪════════════╪═══╪═══════╪═══════╪═══════╪════════════════╡
│ 367104050 ┆ 2020-12-30T00:0 ┆ 34.37833 ┆ -120.16082 ┆ … ┆ 7     ┆ null  ┆ null  ┆ A              │
│           ┆ 0:00            ┆          ┆            ┆   ┆       ┆       ┆       ┆                │
│ 367702780 ┆ 2020-12-30T00:0 ┆ 33.75269 ┆ -118.22173 ┆ … ┆ null  ┆ null  ┆ null  ┆ A              │
│           ┆ 0:00            ┆          ┆            ┆   ┆       ┆       ┆       ┆                │
│ 368064650 ┆ 2020-12-30T00:0 ┆ 33.72366 ┆ -118.27983 ┆ … ┆ null  ┆ null  ┆ null  ┆ A              │
│           ┆ 0:00            ┆          ┆            ┆   ┆       ┆       ┆       ┆                │
│ 367169120 ┆ 2020-12-30T00:0 ┆ 33.71371 ┆ -118.24915 ┆ … ┆ 6     ┆ null  ┆ null  ┆ A              │
│           ┆ 0:00            ┆          ┆            ┆   ┆       ┆       ┆       ┆                │
│ 368072680 ┆ 2020-12-30T00:0 ┆ 33.91221 ┆ -118.44931 ┆ … ┆ null  ┆ null  ┆ null  ┆ A              │
│           ┆ 0:00            ┆          ┆            ┆   ┆       ┆       ┆       ┆                │
└───────────┴─────────────────┴──────────┴────────────┴───┴───────┴───────┴───────┴────────────────┘

In [29]:
df_polar.columns

['MMSI',
 'BaseDateTime',
 'LAT',
 'LON',
 'SOG',
 'COG',
 'Heading',
 'VesselName',
 'IMO',
 'CallSign',
 'VesselType',
 'Status',
 'Length',
 'Width',
 'Draft',
 'Cargo',
 'TransceiverClass']

In [27]:
l = df_polar['VesselName'].str.to_lowercase().unique().to_list()
# MSC Flaminia
# Ever Given
if "ever given" in l:
    print("asdf")

In [35]:
df_filtered = df_polar.filter(pl.col("VesselName") == "TORONADO")
print(df_filtered.shape)

(938, 17)

In [36]:
df_filtered

shape: (938, 17)
┌───────────┬─────────────────┬──────────┬────────────┬───┬───────┬───────┬───────┬────────────────┐
│ MMSI      ┆ BaseDateTime    ┆ LAT      ┆ LON        ┆ … ┆ Width ┆ Draft ┆ Cargo ┆ TransceiverCla │
│ ---       ┆ ---             ┆ ---      ┆ ---        ┆   ┆ ---   ┆ ---   ┆ ---   ┆ ss             │
│ i64       ┆ str             ┆ f64      ┆ f64        ┆   ┆ i64   ┆ f64   ┆ i64   ┆ ---            │
│           ┆                 ┆          ┆            ┆   ┆       ┆       ┆       ┆ str            │
╞═══════════╪═════════════════╪══════════╪════════════╪═══╪═══════╪═══════╪═══════╪════════════════╡
│ 367169120 ┆ 2020-12-30T00:0 ┆ 33.71371 ┆ -118.24915 ┆ … ┆ 6     ┆ null  ┆ null  ┆ A              │
│           ┆ 0:00            ┆          ┆            ┆   ┆       ┆       ┆       ┆                │
│ 367169120 ┆ 2020-12-30T00:0 ┆ 33.71427 ┆ -118.24625 ┆ … ┆ 6     ┆ null  ┆ null  ┆ A              │
│           ┆ 0:00            ┆          ┆            ┆   ┆       ┆       ┆       ┆                │
│ 367169120 ┆ 2020-12-30T00:0 ┆ 33.71527 ┆ -118.24261 ┆ … ┆ 6     ┆ null  ┆ null  ┆ A              │
│           ┆ 1:11            ┆          ┆            ┆   ┆       ┆       ┆       ┆                │
│ 367169120 ┆ 2020-12-30T00:0 ┆ 33.71663 ┆ -118.23913 ┆ … ┆ 6     ┆ null  ┆ null  ┆ A              │
│           ┆ 2:22            ┆          ┆            ┆   ┆       ┆       ┆       ┆                │
│ 367169120 ┆ 2020-12-30T00:0 ┆ 33.71965 ┆ -118.23047 ┆ … ┆ 6     ┆ null  ┆ null  ┆ A              │
│           ┆ 5:12            ┆          ┆            ┆   ┆       ┆       ┆       ┆                │
│ …         ┆ …               ┆ …        ┆ …          ┆ … ┆ …     ┆ …     ┆ …     ┆ …              │
│ 367169120 ┆ 2020-12-30T19:2 ┆ 33.26822 ┆ -119.36453 ┆ … ┆ 6     ┆ null  ┆ null  ┆ A              │
│           ┆ 4:21            ┆          ┆            ┆   ┆       ┆       ┆       ┆                │
│ 367169120 ┆ 2020-12-30T19:2 ┆ 33.26597 ┆ -119.3618  ┆ … ┆ 6     ┆ null  ┆ null  ┆ A              │
│           ┆ 5:31            ┆          ┆            ┆   ┆       ┆       ┆       ┆                │
│ 367169120 ┆ 2020-12-30T21:5 ┆ 33.26137 ┆ -119.40959 ┆ … ┆ 6     ┆ null  ┆ null  ┆ A              │
│           ┆ 5:42            ┆          ┆            ┆   ┆       ┆       ┆       ┆                │
│ 367169120 ┆ 2020-12-30T22:2 ┆ 33.26096 ┆ -119.40771 ┆ … ┆ 6     ┆ null  ┆ null  ┆ A              │
│           ┆ 2:52            ┆          ┆            ┆   ┆       ┆       ┆       ┆                │
│ 367169120 ┆ 2020-12-30T23:5 ┆ 33.26397 ┆ -119.40855 ┆ … ┆ 6     ┆ null  ┆ null  ┆ A              │
│           ┆ 3:02            ┆          ┆            ┆   ┆       ┆       ┆       ┆                │
└───────────┴─────────────────┴──────────┴────────────┴───┴───────┴───────┴───────┴────────────────┘

In [16]:
df_polar['VesselName'].str.contains("INS KOLKATA").count()

6849030

In [21]:
df_1 = df_polar.filter(pl.col("VesselName").str.strip_chars() == "INS KOLKATA")
df_1df_1 = df_polar.filter(
    pl.col("VesselName")
    .str.to_uppercase()
    .str.replace_all(r"\s+", " ")
    .str.strip_chars()
    == "INS KOLKATA"
)
df_1df_1

shape: (0, 17)
┌──────┬──────────────┬─────┬─────┬───┬───────┬───────┬───────┬──────────────────┐
│ MMSI ┆ BaseDateTime ┆ LAT ┆ LON ┆ … ┆ Width ┆ Draft ┆ Cargo ┆ TransceiverClass │
│ ---  ┆ ---          ┆ --- ┆ --- ┆   ┆ ---   ┆ ---   ┆ ---   ┆ ---              │
│ i64  ┆ str          ┆ f64 ┆ f64 ┆   ┆ i64   ┆ f64   ┆ i64   ┆ str              │
╞══════╪══════════════╪═════╪═════╪═══╪═══════╪═══════╪═══════╪══════════════════╡
└──────┴──────────────┴─────┴─────┴───┴───────┴───────┴───────┴──────────────────┘

In [13]:
result = df_polar.filter(pl.col("VesselName").str.to_uppercase() == "INS KOLKATA")
result

shape: (0, 17)
┌──────┬──────────────┬─────┬─────┬───┬───────┬───────┬───────┬──────────────────┐
│ MMSI ┆ BaseDateTime ┆ LAT ┆ LON ┆ … ┆ Width ┆ Draft ┆ Cargo ┆ TransceiverClass │
│ ---  ┆ ---          ┆ --- ┆ --- ┆   ┆ ---   ┆ ---   ┆ ---   ┆ ---              │
│ i64  ┆ str          ┆ f64 ┆ f64 ┆   ┆ i64   ┆ f64   ┆ i64   ┆ str              │
╞══════╪══════════════╪═════╪═════╪═══╪═══════╪═══════╪═══════╪══════════════════╡
└──────┴──────────────┴─────┴─────┴───┴───────┴───────┴───────┴──────────────────┘